### ISSUE TITLE
If prompted, do not accept the beta for version 4 of Ionic. Please use version 3.

### ISSUE THREAD

**Issue by janpio** [BuddyLReno/cordova-plugin-media-duration-demo#1]
What do you mean by that? 

Ionic CLI only prompts for updates of itself, never Ionic Framework. And Ionic CLI 4.x is very safe to use with all Ionic projects.

**Comment by BuddyLReno** [comment]
It's probably overkill, but I've not run it with the Ionic 4 beta. I've only used full releases. I could remove that line.

**Comment by BuddyLReno** [comment]
Removed!

**Comment by janpio** [comment]
Yeah, Ionic 4 beta will not prompt anywhere - there will be manual steps to do. No reason to be afraid of it :)

**Comment by janpio** [comment]
Oh wow:

```
[INFO] You are about to create an Ionic 3 app. Would you like to try Ionic 4 (beta)?

       Ionic 4 uses the power of the modern Web and embraces the Angular CLI and Angular Router to bring you the best
       version of Ionic ever. See our blog announcement[1] and documentation[2] for more information. We'd love to hear
       your feedback on our latest version!

       [1]: https://blog.ionicframework.com/announcing-ionic-4-beta/
       [2]: https://beta.ionicframework.com/docs/
```

WTF.

Think this only appears on `ionic start` though. I hope.

**Comment by BuddyLReno** [comment]
Yeah. I haven't gotten to try this out on Ionic 4 so I'm not sure if things will work.
